'use client';
import {useEffect,useState} from 'react';
import {Bike,CalendarDays,Check,ChevronRight,Coffee,ExternalLink,Hotel,MapPin,Mountain,Navigation,Ship,Sparkles,Utensils,X} from 'lucide-react';
type Stop={time:string;title:string;note:string;ride?:string;type:'ride'|'rest'|'spot'|'food'|'hotel'|'ship';query:string};
const day1:Stop[]=[
{time:'10/9 19:10',title:'神戸港 出航',note:'宮崎カーフェリーで神戸→宮崎へ。乗船番号 622900。',type:'ship',query:'神戸三宮フェリーターミナル'},
{time:'08:40',title:'宮崎港 到着',note:'下船・荷物整理。9:15出発を目安に。',type:'ship',query:'宮崎港フェリーターミナル'},
{time:'10:00',title:'道の駅 フェニックス',note:'日南海岸を眺めながら最初の休憩。日向夏ソフトも。',ride:'約45分',type:'rest',query:'道の駅 フェニックス 宮崎'},
{time:'10:40',title:'サンメッセ日南',note:'丘の上に並ぶ7体のモアイ像と日向灘。滞在45〜50分。',ride:'約30分',type:'spot',query:'サンメッセ日南'},
{time:'11:40',title:'鵜戸神宮',note:'海沿いの参道を歩いて参拝。滞在45〜50分。',ride:'約5分',type:'spot',query:'鵜戸神宮'},
{time:'12:55',title:'とんかつ大晃',note:'昼食は日南のとんかつ専門店で。昼の部は14:00ラストオーダー。',ride:'約30分',type:'food',query:'とんかつ大晃 日南市上平野町'},
{time:'14:05',title:'道の駅 なんごう',note:'食後のデザートにマンゴーソフト。海を眺めて20〜25分休憩。',ride:'約20分',type:'rest',query:'道の駅なんごう 日南市'},
{time:'15:10',title:'都井岬・小松ヶ丘',note:'御崎馬と太平洋の絶景。ゆっくり約60分。',ride:'約40分',type:'spot',query:'都井岬 小松ヶ丘'},
{time:'16:45',title:'道の駅 くしま',note:'ホテルまで一気に走らず20〜30分休憩。',ride:'約35分',type:'rest',query:'道の駅 くしま'},
{time:'18:25',title:'ビジネスホテルしらさぎ',note:'チェックイン後、風呂と着替えでひと休み。',ride:'約1時間15分',type:'hotel',query:'ビジネスホテルしらさぎ 鹿屋'},
{time:'19:30',title:'鹿屋で夕食',note:'第一候補はとんかつ竹亭。うなぎの川豊も候補。',type:'food',query:'とんかつ竹亭 鹿屋本店'}];
const day2:Stop[]=[
{time:'09:00',title:'ホテル出発',note:'フェリー優先で余裕をもってスタート。',type:'ride',query:'ビジネスホテルしらさぎ 鹿屋'},
{time:'09:40',title:'道の駅 たるみずはまびら',note:'桜島を眺めながらコーヒー休憩。約20分。',ride:'約40分',type:'rest',query:'道の駅 たるみずはまびら'},
{time:'10:30',title:'有村溶岩展望所',note:'溶岩原を散策。ここから桜島一周へ。',ride:'約30分',type:'spot',query:'有村溶岩展望所'},
{time:'11:20',title:'黒神埋没鳥居',note:'大正噴火の記憶を残す鳥居。滞在15〜20分。',ride:'約25分',type:'spot',query:'黒神埋没鳥居'},
{time:'12:00',title:'味の里 珍満',note:'桜島で鹿児島らしい昼ごはん。30〜40分で。',ride:'約15分',type:'food',query:'味の里 珍満 桜島'},
{time:'13:00',title:'湯之平展望所',note:'北岳4合目、桜島で最も高い一般立入地点。約25分。',ride:'約25分',type:'spot',query:'湯之平展望所'},
{time:'14:00',title:'道の駅 たるみず',note:'時間に余裕がある場合のみ、10〜15分の最終休憩。',ride:'約45分',type:'rest',query:'道の駅 たるみず 湯っ足り館'},
{time:'15:30',title:'志布志港 到着',note:'15:00受付開始／16:00乗船開始／17:00出港。',ride:'約1時間15分',type:'ship',query:'志布志港 フェリーターミナル'}];
const checks=['免許証・車検証','フェリー予約画面','雨具・防寒インナー','モバイルバッテリー','ETCカード・現金','常備薬・救急用品','タイヤ空気圧チェック','ガソリン満タン'];
const iconMap={ride:Bike,rest:Coffee,spot:Mountain,food:Utensils,hotel:Hotel,ship:Ship};
const maps=(q:string)=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
type Article={lead:string;body:string;highlights:string[];tip:string;image:string;alt:string;credit:string;creditUrl?:string;source?:string};
const articles:Record<string,Article>={
'サンメッセ日南':{lead:'日向灘を見下ろす丘に、イースター島の長老会から許可を得て復刻された7体のモアイ像が並びます。',body:'広い園内には太平洋を望む芝生の丘が広がり、モアイ像の前は南九州ツーリングの記念撮影にぴったり。営業時間は9:30〜17:00（最終入園16:30）、入園料は大人1,000円です。鵜戸神宮とは約5分の距離なので、続けて回れます。',highlights:['7体のモアイ像と日向灘','丘の上からの太平洋ビュー','バイクと一緒の記念撮影'],tip:'園内は坂道が多めです。ライディングブーツで歩くので、滞在は45〜50分を目安に。定休日は水曜日。',image:'./touring-hero.png',alt:'日南海岸のツーリング風景',credit:'AI生成によるオリジナル画像',source:'https://sun-messe.co.jp/information/'},
'神戸港 出航':{lead:'旅の始まりは前夜の神戸から。宮崎カーフェリーで眠っているうちに南九州へ渡ります。',body:'2026年10月9日（金）19:10に神戸を出航し、翌朝8:40に宮崎港へ到着します。バイクは乗船手続きのあと係員の誘導で車両甲板へ。船内に持ち込む荷物（着替え、洗面用具、充電器）は事前にひとまとめにしておくとスムーズです。',highlights:['乗船番号：622900','10/9（金）19:10 神戸発','10/10（土）08:40 宮崎着'],tip:'乗船手続きの締切時刻は予約内容で確認を。バイクは甲板でしっかり固定し、ヘルメットやグローブの置き場所も決めておきましょう。',image:'./touring-hero.png',alt:'南九州へ向かうツーリングのイメージ',credit:'AI生成によるオリジナル画像',source:'https://www.miyazakicarferry.com/schedule/'},
'宮崎港 到着':{lead:'海から始まる南九州ツーリング。港を出た瞬間から、日南海岸へ向かう旅が始まります。',body:'下船後は急いで走り出さず、ミラー、荷物、インカム、ナビを確認。市街地を抜けるまでは交通量があるため、最初の絶景は堀切峠まで取っておくくらいの気持ちで余裕を持ちましょう。',highlights:['下船後に荷物の固定を再確認','出発前にガソリン残量を確認','フェニックスまでは海岸線が見どころ'],tip:'船内で朝食と身支度を済ませておくと、下船後がスムーズです。',image:'./touring-hero.png',alt:'日南海岸を望むツーリングバイク',credit:'AI生成によるオリジナル画像'},
'道の駅 フェニックス':{lead:'「鬼の洗濯板」と青い日向灘を一望できる、日南海岸の定番ビューポイントです。',body:'標高約50mの高台にあり、南国らしいフェニックスの木と海岸線が旅の始まりを盛り上げます。物産館で宮崎の土産を見たり、日向夏やマンゴー系のソフトで短い休憩を取るのにぴったりです。',highlights:['展望デッキから鬼の洗濯板を一望','南国らしい植栽と海の写真','ソフトクリームで糖分補給'],tip:'ここからサンメッセ日南までは潮風を受ける区間。グローブやヘルメットのベンチレーションを調整してから出発を。',image:'./places/phoenix.jpg',alt:'道の駅フェニックスの建物',credit:'Ivan P / Wikimedia Commons / CC0 1.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Michinoeki_Phoenix,_Miyazaki_-_May_2026_(2).jpg',source:'https://www.kanko-miyazaki.jp/spot/1210'},
'鵜戸神宮':{lead:'日向灘に面した断崖の洞窟に、朱塗りの本殿が鎮座する宮崎屈指の名所です。',body:'海沿いの参道を下って洞窟へ向かう「下り宮」が特徴。亀石の枡形に運玉を投げ入れる願掛けでも知られています。駐車場から本殿までは歩くため、ライディングブーツでは足元に注意しましょう。',highlights:['洞窟の中に建つ珍しい本殿','日向灘と朱塗りの欄干','名物の運玉投げ'],tip:'往復の歩きと参拝を含め45〜50分。暑い日は飲み物を持って歩くと安心です。',image:'./places/udo.jpg',alt:'海辺に建つ鵜戸神宮',credit:'JKT-c / Wikimedia Commons / CC BY 3.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Udo-jingu_Shrine.jpg',source:'https://www.kanko-miyazaki.jp/spot/1009'},
'とんかつ大晃':{lead:'日南市街地にあるとんかつ専門店。午後の長い海岸線に備えて、しっかり食べる昼休憩です。',body:'日南市上平野町にある地元で人気のとんかつ店。昼の部は11:00〜14:30（ラストオーダー14:00）。食後は道の駅なんごうへ約20分。デザートのマンゴーソフトは別腹で。',highlights:['揚げたてのとんかつ定食','午後の走行前に水分補給','昼の部LO 14:00に注意'],tip:'定休日は月曜・木曜（10/10の土曜は営業日）。混雑時に備え、鵜戸神宮で押したら早めに向かいましょう。',image:'./places/tonkatsu.jpg',alt:'揚げたてのとんかつ',credit:'Ocdp / Wikimedia Commons / CC0 1.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Tonkatsu_001.jpg',source:'http://www.tonkatsu-taiko.com/'},
'道の駅 なんごう':{lead:'日南海岸の真ん中、太平洋を見下ろす高台の道の駅。名物のマンゴーソフトでひと息つきます。',body:'とんかつ大晃から約20分。南国らしい植物に囲まれた展望スポットで、宮崎産マンゴーを使ったソフトクリームを味わいながら海を眺めます。ここから都井岬までは約40分の海岸線ドライブです。',highlights:['名物のマンゴーソフト','高台から望む日南の海','都井岬前のトイレ休憩'],tip:'以前、旅行期間中の休館予定という情報がありました。営業状況とソフトの販売は出発前に電話（0987-64-3055）で確認を。休館なら栄松ビーチ周辺で小休憩に切り替えます。',image:'./touring-hero.png',alt:'日南海岸のツーリング風景',credit:'AI生成によるオリジナル画像',source:'https://www.michinoeki-nango.jp/'},
'都井岬・小松ヶ丘':{lead:'太平洋を望む草原で、国の天然記念物「御崎馬」が暮らす旅のハイライトです。',body:'御崎馬は約300年前から半野生の状態で暮らしてきた日本在来馬。小松ヶ丘では、青い海、緑の丘、馬が重なる都井岬らしい風景に出会えます。馬は野生動物なので、触れたり食べ物を与えたりせず距離を保って観察します。',highlights:['草原を歩く御崎馬','小松ヶ丘から望む太平洋','岬へ続くワインディング'],tip:'馬が道路上にいることがあります。十分に減速し、驚かせないよう静かに通過してください。',image:'./places/toi.jpg',alt:'都井岬の草原で暮らす御崎馬',credit:'z tanuki / Wikimedia Commons / CC BY 3.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Wild_horse_of_cape_toi._-_%E9%83%BD%E4%BA%95%E5%B2%AC%E3%81%AE%E9%87%8E%E7%94%9F%E9%A6%AC_-_panoramio.jpg',source:'https://www.kanko-miyazaki.jp/spot/1024'},
'道の駅 くしま':{lead:'都井岬を楽しんだあとの、鹿屋までの長い区間に備える休憩拠点です。',body:'串間市街地にあり、地域の農畜産物や土産を見ながら体を休められます。ここからホテルまでは一日の中でも長めの走行になるため、飲み物、トイレ、給油可能距離を必ず確認します。',highlights:['地元の農産物と土産','20〜30分しっかり休憩','鹿屋までの給油計画を確認'],tip:'日没が近づく時間帯です。シールドの汚れを落とし、暗くなる前に出発しましょう。',image:'./touring-hero.png',alt:'南九州の海岸を走るツーリングイメージ',credit:'AI生成によるオリジナル画像',source:'https://michinoeki-kushima.com/'},
'ビジネスホテルしらさぎ':{lead:'一日目のゴール。大浴場とサウナで走行の疲れをほどき、翌日に備えます。',body:'鹿屋市中心部にある宿で、公式案内では無料駐車場を備えています。チェックイン後は荷物を部屋へ運び、濡れた装備やインナーを乾かしてから夕食へ。翌朝の出発が早いので、夜のうちに荷物をまとめておくと安心です。',highlights:['16:00からチェックイン','大浴場・サウナで休息','翌朝9:00出発の準備'],tip:'駐輪場所は到着時にフロントへ確認。鍵や貴重品は必ず部屋へ持ち込みましょう。',image:'./touring-hero.png',alt:'ツーリングバイクと日南海岸',credit:'AI生成によるオリジナル画像',source:'https://www.hotel-shirasagi.jp/'},
'鹿屋で夕食':{lead:'鹿児島らしい一皿で一日を締めくくります。第一候補は地元で親しまれるとんかつです。',body:'とんかつ竹亭を第一候補に、気分を変えたい場合はうなぎの川豊へ。人気店は待ち時間や売り切れも考えられるため、ホテル到着後に営業状況を確認して選びます。バイクを置いて徒歩やタクシーで向かえると、よりゆっくり過ごせます。',highlights:['第一候補はとんかつ竹亭','もう一案はうなぎの川豊','翌朝に備えて食べ過ぎに注意'],tip:'写真はとんかつのイメージです。店舗の料理写真ではありません。',image:'./places/tonkatsu.jpg',alt:'揚げたてのとんかつ',credit:'Ocdp / Wikimedia Commons / CC0 1.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Tonkatsu_001.jpg'},
'ホテル出発':{lead:'二日目は桜島を一周し、15:30までに志布志港へ戻る時間優先の一日です。',body:'出発前に燃料、タイヤ、荷物の固定を確認。桜島では展望所ごとに短く休めますが、午後はフェリーに遅れないことが最優先です。観光が押した場合は、道の駅たるみずの最終休憩を省略します。',highlights:['9:00出発','志布志港15:30着を厳守','観光よりフェリーを優先'],tip:'ナビの到着予想時刻をこまめに確認し、14時には志布志方面へ向かい始めましょう。',image:'./touring-hero.png',alt:'朝のツーリング出発イメージ',credit:'AI生成によるオリジナル画像'},
'道の駅 たるみずはまびら':{lead:'錦江湾越しの桜島を眺めながら、二日目最初のリズムを整える休憩です。',body:'愛称は「たるたるぱあく」。海辺の開放感があり、桜島へ入る前のトイレ・水分補給に向いています。この先は火山景観が続くので、カメラやスマートフォンをすぐ取り出せる位置に準備しておきます。',highlights:['錦江湾と桜島の眺め','コーヒーとトイレ休憩','ここから桜島へ約30分'],tip:'風が強い日はバイクの停め方に注意。傾斜と風向きを見て駐車してください。',image:'./places/arimura.jpg',alt:'桜島と有村溶岩展望所',credit:'鹿児島市 / Wikimedia Commons / CC BY 4.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Arimura_Lava_Observatory_with_Sakurajia.jpg'},
'有村溶岩展望所':{lead:'南岳の麓、溶岩原の中から活火山の迫力を間近に感じる展望所です。',body:'大正溶岩の上に整備された遊歩道から、桜島と錦江湾を見渡せます。風向きによっては噴煙がこちらへ流れることもあり、山の表情が刻々と変わるのが魅力。案内板を読みながら歩くと、溶岩と植生の関係も見えてきます。',highlights:['溶岩原を歩く約1kmの遊歩道','南岳の荒々しい山肌','展望所とバイクの記念写真'],tip:'噴火警戒情報と降灰状況を当日確認。灰がある路面では急操作を避けましょう。',image:'./places/arimura.jpg',alt:'有村溶岩展望所と桜島',credit:'鹿児島市 / Wikimedia Commons / CC BY 4.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Arimura_Lava_Observatory_with_Sakurajia.jpg',source:'https://www.kagoshima-kankou.com/guide/10574'},
'黒神埋没鳥居':{lead:'1914年の大正噴火で、約3mあった鳥居の大部分が火山灰と軽石に埋まった噴火の記憶です。',body:'住民は鳥居を掘り起こそうとしましたが、噴火の脅威を後世へ伝えるため、当時の村長がそのまま保存することを決めました。現在見えているのは笠木部分を中心とした約1m。短い滞在でも桜島の歴史を強く感じられます。',highlights:['地上に残る鳥居の上部','大正噴火を伝える史跡','腹五社神社へ続く参道'],tip:'学校に隣接する静かな場所です。大声を控え、決められた駐車場所を利用しましょう。',image:'./places/torii.jpg',alt:'火山灰に埋もれた黒神埋没鳥居',credit:'Takobou / Wikimedia Commons / CC BY-SA 3.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Sakurajima_buried_torii.jpg',source:'https://www.kagoshima-kankou.com/guide/10531'},
'味の里 珍満':{lead:'地元で長く親しまれる食堂で、午後の走行に備えて手早くしっかり食べます。',body:'桜島観光ポータルでは、チキン南蛮定食やちゃんぽんなど、ボリュームのあるメニューが紹介されています。港へ戻る時間を考え、入店待ちが長い場合は早めに別案へ切り替えるのが安全です。',highlights:['人気のチキン南蛮定食','ちゃんぽんなど豊富な定食','桜洲小学校前の近く'],tip:'写真はチキン南蛮のイメージです。営業状況と混雑は当日確認してください。',image:'./places/chicken-nanban.jpg',alt:'チキン南蛮のイメージ',credit:'Lombroso / Wikimedia Commons / CC BY-SA 4.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Chicken_nanban_(2017-04-28).jpg',source:'https://www.sakurajima.gr.jp/spot/4108.html'},
'湯之平展望所':{lead:'標高373m、一般の人が入れる桜島最高地点から山肌と錦江湾を見渡します。',body:'北岳4合目に位置し、目の前に迫る山の迫力と鹿児島市街地まで広がる眺望が魅力。展望所の石垣には7つのハートが隠されているので、時間に余裕があれば探してみましょう。',highlights:['桜島で最も高い一般立入地点','山と錦江湾のパノラマ','石垣に隠された7つのハート'],tip:'ここを13:30までに出られると安心。写真を撮ったら志布志までの到着予想を再確認します。',image:'./places/yunohira.jpg',alt:'湯之平展望所から望む桜島',credit:'NMaia / Wikimedia Commons / CC BY-SA 4.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Sakurajima_from_Yu_no_Hira.jpg',source:'https://www.kagoshima-kankou.com/guide/10573'},
'道の駅 たるみず':{lead:'全長約60mの足湯でも知られる、錦江湾沿いの道の駅です。',body:'本来は桜島を眺めながらゆっくり休みたい場所ですが、この旅ではフェリー優先の予備休憩。到着予想が15:30を超えそうなら立ち寄らず、そのまま志布志港へ向かいます。',highlights:['桜島を望む足湯','トイレと短い水分補給','立ち寄りは時間に余裕がある時だけ'],tip:'14時を過ぎたら港までの所要時間を最優先。休憩は10〜15分に留めます。',image:'./places/arimura.jpg',alt:'錦江湾から望む桜島',credit:'鹿児島市 / Wikimedia Commons / CC BY 4.0',creditUrl:'https://commons.wikimedia.org/wiki/File:Arimura_Lava_Observatory_with_Sakurajia.jpg',source:'https://www.kagoshima-kankou.com/guide/10570'},
'志布志港 到着':{lead:'二日間のゴール。ここから大阪行きフェリーで旅の余韻を楽しみます。',body:'日曜は17:00出港の予定。バイクは出港60分前までに乗船手続きを完了する必要があるため、15:30到着を目標にしています。港に着いたら予約情報と本人確認書類を準備し、係員の案内に従います。',highlights:['15:30港着目標','16:00までに乗船手続き','17:00出港・翌朝大阪着'],tip:'乗船前に必要な荷物を分け、バイクへ残す物と船室へ持ち込む物を整理しておきましょう。',image:'./touring-hero.png',alt:'南九州ツーリングのゴールイメージ',credit:'AI生成によるオリジナル画像',source:'https://www.ferry-sunflower.co.jp/route/osaka-shibushi/time/'}}
export default function Home(){const[day,setDay]=useState<1|2>(1);const[tab,setTab]=useState<'schedule'|'food'|'check'>('schedule');const[done,setDone]=useState<string[]>([]);const[selected,setSelected]=useState<Stop|null>(null);useEffect(()=>{const s=localStorage.getItem('miyakago-checks');if(s)setDone(JSON.parse(s))},[]);useEffect(()=>{if(!selected)return;const oldOverflow=document.body.style.overflow;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null)};document.body.style.overflow='hidden';window.addEventListener('keydown',close);return()=>{document.body.style.overflow=oldOverflow;window.removeEventListener('keydown',close)}},[selected]);const toggle=(x:string)=>setDone(p=>{const n=p.includes(x)?p.filter(y=>y!==x):[...p,x];localStorage.setItem('miyakago-checks',JSON.stringify(n));return n});const stops=day===1?day1:day2;const article=selected?articles[selected.title]:null;return <main>
<section className="hero"><img src="./touring-hero.png" alt="日南海岸を望むツーリングバイク"/><div className="heroShade"/><div className="heroContent"><p className="eyebrow"><Sparkles size={14}/> MIYAZAKI → KAGOSHIMA</p><h1>海と火山を走る、<br/>2日間。</h1><p className="date"><CalendarDays size={17}/> 2026.10.10 SAT — 10.11 SUN</p></div></section>
<section className="tripSummary"><div><span>2 DAYS</span><strong>宮崎 → 鹿児島</strong></div><div className="summaryDivider"/><div><span>GOAL</span><strong>志布志港 15:30</strong></div></section>
<nav className="tabs" aria-label="アプリメニュー"><button className={tab==='schedule'?'active':''} onClick={()=>setTab('schedule')}><Navigation size={18}/>工程</button><button className={tab==='food'?'active':''} onClick={()=>setTab('food')}><Utensils size={18}/>グルメ</button><button className={tab==='check'?'active':''} onClick={()=>setTab('check')}><Check size={18}/>準備</button></nav>
{tab==='schedule'&&<section className="content"><div className="daySwitch"><button className={day===1?'selected':''} onClick={()=>setDay(1)}><b>DAY 1</b><span>モアイ・鵜戸・都井岬</span></button><button className={day===2?'selected':''} onClick={()=>setDay(2)}><b>DAY 2</b><span>桜島一周・志布志</span></button></div><div className="notice"><Coffee size={18}/><p><b>休憩多めの安心プラン</b><br/>カードをタップすると、写真付きの紹介記事が開きます。</p></div><div className="timeline">{stops.map((s,i)=>{const Icon=iconMap[s.type];const open=()=>setSelected(s);return <article className="stop" key={s.time+s.title}><div className={`stopIcon ${s.type}`}><Icon size={19}/></div><div className="stopBody" role="button" tabIndex={0} onClick={open} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}} aria-label={`${s.title}の紹介記事を開く`}><div className="stopOpen"><div className="stopTop"><time>{s.time}</time>{s.ride&&<span>🏍 {s.ride}</span>}</div><h2>{s.title}<ChevronRight size={18}/></h2><p>{s.note}</p><small>写真と見どころを見る</small></div><a href={maps(s.query)} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}><Navigation size={16}/>ナビで開く<ChevronRight size={16}/></a></div>{i<stops.length-1&&<div className="line"/>}</article>})}</div></section>}
{tab==='food'&&<section className="content foodGrid"><header className="sectionHead"><span>LOCAL FOOD</span><h2>旅のごはん</h2><p>営業時間と定休日は出発前に再確認してください。</p></header>{[['DAY 1・昼','とんかつ大晃','日南のとんかつ定食','とんかつ大晃 日南市上平野町'],['DAY 1・夜 第一候補','とんかつ竹亭 鹿屋本店','鹿児島のとんかつ','とんかつ竹亭 鹿屋本店'],['DAY 1・夜 もう一案','うなぎの川豊','うな重・うな丼','うなぎの川豊 鹿屋'],['DAY 2・昼','味の里 珍満','桜島ランチ','味の里 珍満 桜島']].map(([label,name,dish,q])=><article className="foodCard" key={name}><span>{label}</span><h3>{name}</h3><p>{dish}</p><a href={maps(q)} target="_blank" rel="noreferrer"><MapPin size={16}/>地図を見る<ExternalLink size={14}/></a></article>)}<div className="ferryCard"><Ship size={24}/><div><span>OUTBOUND FERRY</span><h3>神戸 10/9 19:10 → 宮崎 08:40</h3><p>宮崎カーフェリー／乗船番号 622900</p></div></div><div className="ferryCard"><Ship size={24}/><div><span>RETURN FERRY</span><h3>志布志 17:00 → 大阪 07:40</h3><p>15:30港着を厳守。バイクの乗船手続きは出港60分前まで。</p></div></div></section>}
{tab==='check'&&<section className="content"><header className="sectionHead"><span>BEFORE YOU RIDE</span><h2>出発前チェック</h2><p>{done.length} / {checks.length} 完了</p></header><div className="progress"><i style={{width:`${done.length/checks.length*100}%`}}/></div><div className="checkList">{checks.map(x=><button key={x} onClick={()=>toggle(x)} className={done.includes(x)?'done':''}><i><Check size={16}/></i><span>{x}</span></button>)}</div><button className="reset" onClick={()=>{setDone([]);localStorage.removeItem('miyakago-checks')}}>すべてリセット</button></section>}
<footer>安全運転で、よい旅を。<br/><small>天候・道路・営業時間は当日に再確認してください。</small></footer>
{selected&&article&&<div className="articleBackdrop" onClick={()=>setSelected(null)}><section className="articlePanel" role="dialog" aria-modal="true" aria-labelledby="article-title" onClick={e=>e.stopPropagation()}><header className="articleHeader"><div className="articleTime"><span>{selected.time}</span>{selected.ride&&<small>🏍 {selected.ride}</small>}</div><h2 id="article-title" className="articleTitle">{selected.title}</h2><p className="articleLead">{article.lead}</p><button type="button" className="articleClose" onClick={()=>setSelected(null)} aria-label="記事を閉じる"><X size={22}/></button></header><div className="articleScroll"><figure><img src={article.image} alt={article.alt}/><figcaption>{article.creditUrl?<a href={article.creditUrl} target="_blank" rel="noreferrer">Photo: {article.credit}</a>:article.credit}</figcaption></figure><p className="articleBody">{article.body}</p><section className="articleHighlights"><h3>ここで楽しみたいこと</h3><ul>{article.highlights.map(x=><li key={x}><Check size={17}/><span>{x}</span></li>)}</ul></section><aside className="riderTip"><Bike size={21}/><div><strong>ライダー向けメモ</strong><p>{article.tip}</p></div></aside><div className="articleActions"><a href={maps(selected.query)} target="_blank" rel="noreferrer"><Navigation size={18}/>この場所へナビ</a>{article.source&&<a className="sourceLink" href={article.source} target="_blank" rel="noreferrer"><ExternalLink size={16}/>公式・参考情報</a>}</div></div></section></div>}
</main>}
